docker.sources = file-source
docker.sinks = kafka-sink
docker.channels = memory-channel

docker.sources.file-source.type = TAILDIR
docker.sources.file-source.positionFile = /var/log/flume-ng/taildir_position.json
docker.sources.file-source.filegroups = retailpulse
docker.sources.file-source.filegroups.retailpulse = /var/log/flume_lab/retailpulse/.*\.json
docker.sources.file-source.channels = memory-channel

docker.channels.memory-channel.type = memory
docker.channels.memory-channel.capacity = 10000
docker.channels.memory-channel.transactionCapacity = 1000

docker.sinks.kafka-sink.type = org.apache.flume.sink.kafka.KafkaSink
docker.sinks.kafka-sink.kafka.topic = retailpulse-events
docker.sinks.kafka-sink.kafka.bootstrap.servers = 07-01-kafka:9092
docker.sinks.kafka-sink.kafka.flumeBatchSize = 100
docker.sinks.kafka-sink.channel = memory-channel
